version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: glov
      POSTGRES_USER: emrehanaydin
      POSTGRES_PASSWORD: 300718cc
    ports:
      - "5432:5432"
    volumes:
      - "./embedding.sql:/docker-entrypoint-initdb.d/embedding.sql"

  app:
    build: .
    container_name: app
    command: >
             uvicorn api.main:app --reload --host 0.0.0.0 --port 8000

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx.conf:/etc/nginx/conf.d/server.conf


volumes:
  postgres_data: